### PR TITLE
Update Storybook to the latest stable version

### PR DESCRIPTION
**Pull request by vmilan**
# Description

Shortcut: not yet

As we have some issues with v7 alpha (not compatible with the Figma addon right now), just update to the latest version of Storybook.

## Type of change

- Refactor

### CODE REVIEW

**Review by VictorVelarde — APPROVED** [review]
LGTM, just add a small note to changelog, please

**Comment by vmilan** [comment]
Ok! Changelog updated

**Review by bbecquet — COMMENTED** [review]
The code changes look ok but I'm faced with this issue when trying to install the new Storybook locally: 
```
error An unexpected error occurred: "ENAMETOOLONG: name too long, unlink '/home/benjamin/.cache/yarn/v6/npm-@storybook-react-docgen-typescript-plugin-1.0.2-canary.6.9d540b91e815f8fc2f8829189deb00553559ff63.0-3103532ff494fb7dc3cf835f10740ecf6a26c0f9-integrity/node_modules/@storybook/react-docgen-typescript-plugin'".
```
This is a [reported issue in Storybook](https://github.com/storybookjs/storybook/discussions/18441), with a proposed workaround, but I hope it won't happen again as this workaround is really fragile.

**Comment by vmilan** [comment]
I didn't have that issue in my local environment. I think is not a common issue, but let me know if you want to do something with this PR or I can merge

**Review by bbecquet — APPROVED** [review]
@vmilan
> I didn't have that issue in my local environment. I think is not a common issue, but let me know if you want to do something with this PR or I can merge

Ok for me to merge :+1:. There is not much you can do anyway and I have a functional workaround for now.

**Pull request merged**
