### PR TITLE
Improve styles for MaterialUI - Dialog component

### PR DESCRIPTION
**Pull request by builtbyedgar**
Shortcut: https://app.shortcut.com/cartoteam/story/145205/component-dialogs-modals

### CODE REVIEW

**Review by Josmorsot — CHANGES_REQUESTED** [review]
When you open this story appears the next thing:
image

@builtbyedgar Could you take a look?

**Comment by VictorVelarde** [comment]
@builtbyedgar if you can't currently work in the project, ping us so we can see how to manage CR changes

**Comment by Josmorsot** [comment]
Acceptance OK

**Comment by VictorVelarde** [comment]
@Josmorsot. You should take this one, when you can

**Review by Josmorsot — APPROVED** [review]

**Pull request merged**
