### PR TITLE
Improve styles for MaterialUI - ToggleButton & ToggleButtonGroup components

### PR DESCRIPTION
**Pull request by builtbyedgar**
Implement the Carto theme for Toggle Button of Material UI with the current design

Story: [Component - Toggle button](https://app.shortcut.com/cartoteam/story/140023/component-toggle-button)

### CODE REVIEW

**Review by Josmorsot — APPROVED** [review]
LGTM

**Review by VictorVelarde — CHANGES_REQUESTED** [review]
No yarn.lock change should be needed for this. I'll remove it

**Comment by VictorVelarde** [comment]
In the future please 3 small additions to any PR: link the original task / add changelog entry and give PR a bit cleaner name.

**Comment by VictorVelarde** [comment]
Code LGTM. Please @Josmorsot help us on acceptance, with link version from carto-3, to see if we can land this on wednesday

**Review by VictorVelarde — COMMENTED** [review]
LGTM, but we need to run some acceptance with carto-3 before landing. We'll do it asap

**Comment by Josmorsot** [comment]
@VictorVelarde acceptance OK, we can merge

**Review by VictorVelarde — APPROVED** [review]
👍🏻

**Comment by borja-munoz** [comment]
[sc-140023]

**Pull request merged**
