### PR TITLE
Add NoDataAlert widget

### PR DESCRIPTION
**Pull request by Clebal**
Story details: https://app.shortcut.com/cartoteam/story/183641

### CODE REVIEW

**Comment by VictorVelarde** [comment]
I've added it also to FormulaWidget, for consistency (and because default 0.00 value for empty might be wrong / misleading under certain operations). I also reduced a bit the IMO very long text (@borja-munoz can maybe give us feedback on that during QA)

image

**Review by VictorVelarde — APPROVED** [review]
LGTM, so 🚀

**Comment by Clebal** [comment]
Sorry @VictorVelarde, I don't agree. From my experience in PS projects, when the count of elements is 0, the client wants to see 0, no "No data". That's why I didn't added there.

Another example, if the sum of revenue of a certain store is 0, it isn't the same as no data.

**Comment by VictorVelarde** [comment]
I understand that displaying 0.0 might be find assuming Count or Sum, but there are other operations that can be applied to Formula, where 0 is not, IMO, fine. Having said that I have no issues in reverting that commit, let's just ping @borja-munoz for confirmation on this before merging it

**Comment by VictorVelarde** [comment]
I'm gonna do one thing, I'm gonna revert my commit, so to merge this as Sergio set it, and if Borja wants to include my FormulaWidget change, we can do another PR with cherry-pick later

**Comment by borja-munoz** [comment]
I think for COUNT operations makes sense to show 0 if there is no data in the current viewport. For the other aggregation operations (SUM, AVG, MIN, MAX), I think it is better to show the no data message.

Sorry for introducing a third option. If there is no time now to implement it, I'd keep Sergio's approach for now, but revisit this in the future.

**Pull request merged**
