### PR TITLE
Update Storybook to v7-alpha to get ready for design system

### PR DESCRIPTION
**Pull request by vmilan**
# Description

Shortcut: there is no shortcut card yet.

Updating Storybook from v6.4.14 to 7.0.0-alpha.34 (as 7 should be the stable version in a couple of months).

Also clean up of complex components, that are out of scope by now. We'll be included as we need them.

## Type of change

- Refactor

### CODE REVIEW

**Review by Josmorsot — APPROVED** [review]

**Comment by vmilan** [comment]
@VictorVelarde it is ok for you to merge into the experimental branch or do you still prefer to merge into main?

**Comment by VictorVelarde** [comment]
If it can be landed in main, I would, but before doing it I would like to see it with more calm

**Review by VictorVelarde — CHANGES_REQUESTED** [review]
Let me check with a bit of detail, before landing

**Comment by VictorVelarde** [comment]
Please @vmilan let broken stories commented, not removed, and then you can land into the DS branch

**Comment by vmilan** [comment]
@VictorVelarde changes requested are done, please take a look when you can. Thanks!

**Comment by vmilan** [comment]
I've found an issue with the design addon that we need to embed Figma designs in Storybook. I opened an issue in their GitHub repository and I'll wait to see if it solves in further versions. By now I'm closing this PR.

**Comment by VictorVelarde** [comment]
@vmilan can you please link the issue at their repo here, so we can have tracebility?

**Comment by vmilan** [comment]
Sure, this is the issue: https://github.com/pocka/storybook-addon-designs/issues/171

It seems fixed, let's see when we install the new storybook in CN

**Pull request closed without merging**
