### PR TITLE
Add tooltip prop to Comparative Category Widget

### PR DESCRIPTION
**Pull request by menusal**
# Description

Add control to disable or enable hover listener for `ComparativeCategoryWidget`

Default `tooltip` prop value set to `true` 

image
image
_Storybook snapshots_

## Type of change

- Feature

## Acceptance

1. Go to storybook http://localhost:6006/?path=/docs/organisms-widgets-comparativecategorywidgetui--default
2. Test the toggle button.
3. Assert if the tooltip matches visibility with the toggle value.

### CODE REVIEW

**Review by juandjara — APPROVED** [review]
LGTM

**Review by VictorVelarde — APPROVED** [review]
Please add a note to changelog and we'll land it @menusal. Thx!

**Comment by menusal** [comment]
> Please add a note to changelog and we'll land it @menusal. Thx!

Done! @VictorVelarde

**Review by VictorVelarde — APPROVED** [review]
👍🏻

**Pull request merged**
