### PR TITLE
SelectField: extend to accept more data structures as children and to fix placeholder

### PR DESCRIPTION
**Pull request by vmilan**
# Description

Shortcut: https://app.shortcut.com/cartoteam/story/352074/cn-replace-old-code-with-selectfield-component
[sc-352074]

### CODE REVIEW

**Comment by zbigg** [comment]
MultipleSelect seems to have excessive padding and extra colon at end (old bug)

image

**Comment by zbigg** [comment]
(old bug) Multiple Select Field in medium has same height as small, only text changes

image

**Review by VictorVelarde — APPROVED** [review]
Code changes LGTM. Do we have Design check over storybook?

PD. Let's be a bit more verbose about the new 'supported use cases', at least in CHANGELOG

**Comment by vmilan** [comment]
> Code changes LGTM. Do we have Design check over storybook?
> 
> PD. Let's be a bit more verbose about the new 'supported use cases', at least in CHANGELOG

No, since they are going to review in the dedicated, I didn't want to overwhelm them with several reviews of the same thing.

Changed changelog and PR title.

**Comment by vmilan** [comment]
> MultipleSelect seems to have excessive padding and extra colon at end (old bug)
> 
> image

After our conversation, I decided not to export Multiple SelectField for now until we solve these errors and improve the component, hopefully next Q.

**Pull request merged**
